#:kivy 1.0
#:import kivy kivy
#:import win kivy.core.window

Root:
    canvas:
        Color:
            rgb: 1, 1, 1
    BoxLayout:
        orientation: 'vertical'
        canvas:
            Rectangle:
                source: 'resources/ev2.png'
                size: self.size
        BoxLayout:
            size_hint_y: None
            height: 30
            pos: 50, 50
            Image:
                size_hint: None, None
                size: 24, 24
                source: 'data/logo/kivy-icon-24.png'
            Button:
                pos: 0, 0
                text: 'Load'
                on_release: root.show_load()
            Button:
                text: 'Save'
                on_release: root.show_save()
            Button:
                text: 'Start Line'
                on_release: root.start_line()
            Button:
                text: 'End Line'
                on_release: root.end_line()
            Button:
                text: 'Clear Line'
                on_release: root.clear_line()


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)


<Picture>:
    # each time a picture is created, the image can delay the loading
    # as soon as the image is loaded, ensure that the center is changed
    # to the center of the screen.
    on_size: self.center = win.Window.center
    size: image.size
    size_hint: None, None

    Image:
        id: image
        source: root.source

        # create initial image to be 400 pixels width
        size: 400, 400 / self.image_ratio

        # add shadow background
        canvas.before:
            Color:
                rgba: 1,1,1,1
            BorderImage:
                source: 'resources/shadow32.png'
                border: (36,36,36,36)
                size:(self.width+72, self.height+72)
                pos: (-36,-36)
